kind: Deployment
apiVersion: apps/v1
metadata:
  name: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: tomcat
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: 'tomcat'
          tag: 'latest'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
